### ISSUE TITLE
Setup instructions are missing

### ISSUE THREAD

**Issue by gagb** [successar/Eraser-Benchmark-Baseline-Models#2]
Hi Jay/Sarthak,

Thank you for releasing this codebase. Our lab is trying to use your re-implementation of Lei et. al.'s model. Unfortunately we've had little success getting this code base to even setup. For example, ``pip install -r requirements.txt`` fails. Further, there seem to be many dependency issues: It seems like you are using a custom fork of AllenNLP which installs pytorch 1.4.0, which conflicts with the version you specify in ``requirements.txt``(1.3.0). Also, it seems that your custom AllenNLP fork has been updated since this codebase was released?? What version of it should we use?

Are you able to setup and run the code with the instructions in your ``README.md``? Can you please update them? 

Again, thank you for releasing this codebase and we look forward towards your response.

-Gagan

**Comment by successar** [comment]
Hi Gagan,

We will soon be releasing (by next week) new updates to this codebase that will have the correct allennlp code in it.

**Comment by successar** [comment]
I have updated the codebase with the allennlp within this repository. Please let me know if you are still facing any problems.
